DELETE FROM ESTADO_PROCESO;
DELETE FROM CITAS;
DELETE FROM DOSIS;

DELETE FROM CIUDADANOS;
DELETE FROM OPERADOR_PUNTO_VACUNACION;
DELETE FROM ADMIN_PUNTO_VACUNACION;

DELETE FROM ADMIN_EPS;
DELETE FROM ADMIN_PLAN_VACUNACION;
DELETE FROM CONTRASENA_FUNCIONARIOS;
DELETE FROM PUNTO_VACUNACION;
DELETE FROM ESTADO_DE_SALUD;
DELETE FROM PROFESION;

DELETE FROM FUNCIONARIOS;
DELETE FROM OFICINA_EPS_REGIONAL;

UPDATE VACUNACION
SET IDETAPA_ACTUAL=NULL;

DELETE FROM ETAPA;
DELETE FROM RESTRICCIONES;
DELETE FROM NUMERO_DOSIS_VACUNA;

DELETE FROM VACUNACION;
DELETE FROM VACUNA;
DELETE FROM VENCIMIENTO_DOSIS;

COMMIT;