-- Creación del secuenciador
create sequence Vacuandes_sequence;

-- Creaación de la tabla VENCIMIENTO_DOSIS y especificación de sus restricciones
CREATE TABLE VENCIMIENTO_DOSIS
    (LOTE VARCHAR2(20 BYTE),
    FECHAVENCIMIENTO DATE NOT NULL,
    CONSTRAINT PK_VENCIMIENTO_DOSIS PRIMARY KEY(LOTE));
    
--Creación de la tabla ESTADOS_POSIBLES y especificación de sus restricciones
CREATE TABLE ESTADOS_POSIBLES
    (ID NUMBER,
    DESCRIPCION VARCHAR2(50 BYTE) NOT NULL,
    CONSTRAINT PK_ESTADOS_POSIBLES PRIMARY KEY(ID));
    
ALTER TABLE ESTADOS_POSIBLES
    ADD CONSTRAINT UN_EP_DESCRIPCION
    UNIQUE (DESCRIPCION)
ENABLE;
    
-- Creaación de la tabla VACUNA y especificación de sus restricciones
CREATE TABLE VACUNA
    (ID NUMBER,
    NOMBRE VARCHAR2(50 BYTE) NOT NULL,
    REQUERIMIENTOSDEALMACENAMIENTO VARCHAR2(50 BYTE) NOT NULL,
    CONSTRAINT PK_VACUNA PRIMARY KEY(ID));

ALTER TABLE VACUNA
    ADD CONSTRAINT UN_NOMBRE
    UNIQUE(NOMBRE)
ENABLE;

-- Creaación de la tabla VACUNACION y especificación de sus restricciones
CREATE TABLE VACUNACION
    (ID NUMBER,
    DOSIS_TOTALES NUMBER NOT NULL,
    DOSIS_APLICADAS NUMBER NOT NULL,
    DOSIS_PERDIDAS NUMBER NOT NULL,
    IDETAPA_ACTUAL NUMBER,
    CONSTRAINT PK_VACUNACION PRIMARY KEY (ID));
    
ALTER TABLE VACUNACION
	ADD CONSTRAINT CK_DOS_TOT 
	CHECK (DOSIS_TOTALES >= 0)
ENABLE;
    
ALTER TABLE VACUNACION
    ADD CONSTRAINT CK_DOS_APL
	CHECK (DOSIS_APLICADAS >= 0)
ENABLE;

ALTER TABLE VACUNACION
    ADD CONSTRAINT CK_DOS_PER
	CHECK (DOSIS_PERDIDAS >= 0)
ENABLE;

-- Creaación de la tabla NUMERO_DOSIS_VACUNA y especificación de sus restricciones
CREATE TABLE NUMERO_DOSIS_VACUNA
    (ID NUMBER,
    NUMERODOSIS NUMBER NOT NULL,
    CONSTRAINT PK_NUMERO_DOSIS PRIMARY KEY(ID));

ALTER TABLE NUMERO_DOSIS_VACUNA
    ADD CONSTRAINT FK_NDV_VACUNA
    FOREIGN KEY (ID)
    REFERENCES VACUNA(ID)
ENABLE;

ALTER TABLE NUMERO_DOSIS_VACUNA
    ADD CONSTRAINT CK_NUM_DOSIS_VAC
    CHECK (NUMERODOSIS > 0)
ENABLE;

-- Creaación de la tabla RESTRICCIONES y especificación de sus restricciones
CREATE TABLE RESTRICCIONES
    (ID NUMBER,
    DESCRIPCION VARCHAR2(250 BYTE) NOT NULL,
    IDVACUNA NUMBER NOT NULL,
    CONSTRAINT PK_RESTRICCIONES PRIMARY KEY(ID));
    
ALTER TABLE RESTRICCIONES
    ADD CONSTRAINT FK_R_VACUNA
    FOREIGN KEY (IDVACUNA)
    REFERENCES VACUNA(ID)
ENABLE;

-- Creaación de la tabla ETAPA y especificación de sus restricciones
CREATE TABLE ETAPA
    (ID NUMBER,
    FASE NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(500 BYTE) NOT NULL,
    EDAD_MINIMA NUMBER NOT NULL,
    EDAD_MAXIMA NUMBER NOT NULL,
    IDVACUNACION NUMBER NOT NULL,
    CONSTRAINT PK_ETAPA PRIMARY KEY (ID));

ALTER TABLE ETAPA
    ADD CONSTRAINT CK_FASE
    CHECK (FASE > 0)
ENABLE;

ALTER TABLE ETAPA
    ADD CONSTRAINT UN_DESCRIPCION
    UNIQUE (DESCRIPCION)
ENABLE;

ALTER TABLE ETAPA
    ADD CONSTRAINT CK_EDAD_MINIMA
    CHECK (EDAD_MINIMA >= 0)
ENABLE;

ALTER TABLE ETAPA
    ADD CONSTRAINT CK_EDAD_MAXIMA
    CHECK (EDAD_MAXIMA >= EDAD_MINIMA)
ENABLE;

ALTER TABLE ETAPA
    ADD CONSTRAINT FK_E_VACUNACION
    FOREIGN KEY (IDVACUNACION)
    REFERENCES VACUNACION(ID)
ENABLE;

--Creación de FK de ETAPA en la tabla VACUNACION
ALTER TABLE VACUNACION
    ADD CONSTRAINT FK_ETAPA_ACTUAL
    FOREIGN KEY (IDETAPA_ACTUAL)
    REFERENCES ETAPA(ID)
ENABLE;

-- Creaación de la tabla OFICINA_EPS_REGIONAL y especificación de sus restricciones  
CREATE TABLE OFICINA_EPS_REGIONAL
    (ID NUMBER,
    NOMBRE VARCHAR2(50 BYTE) NOT NULL,
    NIT VARCHAR2(12 BYTE) NOT NULL,
    REGION VARCHAR2 (25 BYTE) NOT NULL,
    DIRECCION VARCHAR2(50 BYTE) NOT NULL,
    NUMERO_CONTACTO NUMBER NOT NULL,
    CIUDAD VARCHAR2(25 BYTE) NOT NULL,
    IDVACUNACION NUMBER NOT NULL,
    CONSTRAINT PK_OFICINA_EPS_REGIONAL PRIMARY KEY(ID));

ALTER TABLE OFICINA_EPS_REGIONAL
    ADD CONSTRAINT UN_NIT
    UNIQUE (NIT)
ENABLE;

ALTER TABLE OFICINA_EPS_REGIONAL
    ADD CONSTRAINT FK_OER_VACUNACION
    FOREIGN KEY (IDVACUNACION)
    REFERENCES VACUNACION(ID)
ENABLE;

-- Creaación de la tabla FUNCIONARIOS y especificación de sus restricciones
CREATE TABLE FUNCIONARIOS
    (ID NUMBER,
    CORREO VARCHAR2(30 BYTE) NOT NULL,
    ID_VACUNACION NUMBER NOT NULL,
    CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY(ID));
    
ALTER TABLE FUNCIONARIOS
    ADD CONSTRAINT UN_CORREO
    UNIQUE(CORREO)
ENABLE;

ALTER TABLE FUNCIONARIOS
    ADD CONSTRAINT FK_F_VACUNACION
    FOREIGN KEY (ID_VACUNACION)
    REFERENCES VACUNACION(ID)
ENABLE;

-- Creaación de la tabla PROFESION y especificación de sus restricciones
CREATE TABLE PROFESION
    (ID NUMBER,
    DESCRIPCION VARCHAR2 (250 BYTE) NOT NULL,
    IDETAPA NUMBER NOT NULL,
    CONSTRAINT PK_PROFESION PRIMARY KEY(ID));

ALTER TABLE PROFESION
    ADD CONSTRAINT FK_P_ETAPA
    FOREIGN KEY (IDETAPA)
    REFERENCES ETAPA(ID)
ENABLE;


-- Creaación de la tabla ESTADO_DE_SALUD y especificación de sus restricciones  
CREATE TABLE ESTADO_DE_SALUD
    (ID NUMBER,
    DESCRIPCION VARCHAR2(250 BYTE) NOT NULL,
    IDETAPA NUMBER NOT NULL,
    CONSTRAINT PK_ESTADO_DE_SALUD PRIMARY KEY (ID));
    
ALTER TABLE ESTADO_DE_SALUD
    ADD CONSTRAINT FK_ES_ETAPA
    FOREIGN KEY (IDETAPA)
    REFERENCES ETAPA(ID)
ENABLE;

-- Creaación de la tabla PUNTO_VACUNACION y especificación de sus restricciones  
CREATE TABLE PUNTO_VACUNACION
    (ID NUMBER,
    LOCALIZACION VARCHAR2(50 BYTE)NOT NULL,
    CUPOMAXIMO NUMBER NOT NULL,
    MAXCIUDADANOSPORDIA NUMBER NOT NULL,
    TOTALVACUNADOS NUMBER NOT NULL,
    INFRAESTRUCTURAALMACENAMIENTO VARCHAR2(50 BYTE) NOT NULL,
    CAPACIDADALMACENAMIENTODOSIS NUMBER NOT NULL,
    ESTAHABILITADO NUMBER NOT NULL,
    IDEPSREGIONAL NUMBER NOT NULL,
    CONSTRAINT PK_PUNTO_VACUNACION PRIMARY KEY(ID));

ALTER TABLE PUNTO_VACUNACION
    ADD CONSTRAINT CK_CUPO_MAX
    check(MAXCIUDADANOSPORDIA >=0)
ENABLE;

ALTER TABLE PUNTO_VACUNACION
    ADD CONSTRAINT CK_MAX_CIUD_X_DIA
    check(CUPOMAXIMO >=0)
ENABLE;

ALTER TABLE PUNTO_VACUNACION
    ADD CONSTRAINT CK_TOT_VACUN
    check(TOTALVACUNADOS >=0)
ENABLE;

ALTER TABLE PUNTO_VACUNACION
    ADD CONSTRAINT CK_CAPACIDAD_DOSIS
    check(CAPACIDADALMACENAMIENTODOSIS >=0)
ENABLE;

ALTER TABLE PUNTO_VACUNACION
    ADD CONSTRAINT FK_PV_OFICINA_EPS
    FOREIGN KEY (IDEPSREGIONAL)
    REFERENCES OFICINA_EPS_REGIONAL(ID)
ENABLE;

ALTER TABLE PUNTO_VACUNACION
    ADD CONSTRAINT CK_HABILITADO_PV
    CHECK (ESTAHABILITADO IN (0,1))
ENABLE;

--Creacion de la tabla CAMBIOS_PUNTO_VACUNACION
CREATE TABLE CAMBIOS_PUNTO_VACUNACION
    (ID NUMBER,
    DISPONIBLE NUMBER NOT NULL,
    FECHACAMBIO DATE NOT NULL,
    COMENTARIOS VARCHAR2(250 BYTE),
    ID_PUNTO_VACUNACION NUMBER NOT NULL,
    CONSTRAINT PK_CAMBIOS_PUNTO_VACUNACION PRIMARY KEY(ID));

    
ALTER TABLE CAMBIOS_PUNTO_VACUNACION
    ADD CONSTRAINT CK_DISPONIBLE_CPV
    CHECK (DISPONIBLE IN (0,1))
ENABLE;

ALTER TABLE CAMBIOS_PUNTO_VACUNACION
    ADD CONSTRAINT FK_CPV_PUNTO_VACUNACION
    FOREIGN KEY (ID_PUNTO_VACUNACION)
    REFERENCES PUNTO_VACUNACION(ID)
ENABLE;
    

-- Creaación de la tabla CONTRASENA_FUNCIONARIOS y especificación de sus restricciones
CREATE TABLE CONTRASENA_FUNCIONARIOS
    (ID_FUNCIONARIO NUMBER,
    CONTRASENA VARCHAR2(20 BYTE) NOT NULL,
    CONSTRAINT PK_CONTRASENA_FUNCIONARIOS PRIMARY KEY(ID_FUNCIONARIO));
    
ALTER TABLE CONTRASENA_FUNCIONARIOS
    ADD CONSTRAINT FK_CF_FUNCIONARIOS
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIOS(ID)
ENABLE;

-- Creaación de la tabla ADMIN_PLAN_VACUNACION y especificación de sus restricciones
CREATE TABLE ADMIN_PLAN_VACUNACION
    (ID_FUNCIONARIO NUMBER,
    ID_PLAN_VACUNACION NUMBER NOT NULL,
    CONSTRAINT PK_ADMIN_PLAN_VACUNACION PRIMARY KEY(ID_FUNCIONARIO));
    
ALTER TABLE ADMIN_PLAN_VACUNACION
    ADD CONSTRAINT FK_APV_VACUNACION
    FOREIGN KEY (ID_PLAN_VACUNACION)
    REFERENCES VACUNACION(ID)
ENABLE;

ALTER TABLE ADMIN_PLAN_VACUNACION
    ADD CONSTRAINT FK_APLV_FUNCIONARIO
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIOS(ID)
ENABLE;

-- Creaación de la tabla ADMIN_EPS y especificación de sus restricciones
CREATE TABLE ADMIN_EPS
    (ID_FUNCIONARIO NUMBER,
    ID_OFICINA_EPS NUMBER NOT NULL,
    CONSTRAINT PK_ADMIN_EPS PRIMARY KEY(ID_FUNCIONARIO));
    
ALTER TABLE ADMIN_EPS
    ADD CONSTRAINT FK_AE_OFICINA_EPS
    FOREIGN KEY (ID_OFICINA_EPS)
    REFERENCES OFICINA_EPS_REGIONAL(ID)
ENABLE;

ALTER TABLE ADMIN_EPS
    ADD CONSTRAINT FK_AE_FUNCIONARIO
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIOS(ID)
ENABLE;

-- Creaación de la tabla ADMIN_PUNTO_VACUNACION y especificación de sus restricciones
CREATE TABLE ADMIN_PUNTO_VACUNACION
    (ID_FUNCIONARIO NUMBER,
    ID_PUNTO_VACUNACION NUMBER NOT NULL,
    CONSTRAINT PK_ADMIN_PUNTO_VACUNACION PRIMARY KEY(ID_FUNCIONARIO));
    
ALTER TABLE ADMIN_PUNTO_VACUNACION
    ADD CONSTRAINT FK_APV_PUNTO_VACUNACION
    FOREIGN KEY (ID_PUNTO_VACUNACION)
    REFERENCES PUNTO_VACUNACION(ID)
ENABLE;

ALTER TABLE ADMIN_PUNTO_VACUNACION
    ADD CONSTRAINT FK_APUV_FUNCIONARIO
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIOS(ID)
ENABLE;

-- Creaación de la tabla OPERADOR_PUNTO_VACUNACION y especificación de sus restricciones
CREATE TABLE OPERADOR_PUNTO_VACUNACION
    (ID_FUNCIONARIO NUMBER,
    ID_PUNTO_VACUNACION NUMBER NOT NULL,
    CONSTRAINT PK_OPERADOR_PUNTO_VACUNACION PRIMARY KEY(ID_FUNCIONARIO));
    
ALTER TABLE OPERADOR_PUNTO_VACUNACION
    ADD CONSTRAINT FK_OPV_PUNTO_VACUNACION
    FOREIGN KEY (ID_PUNTO_VACUNACION)
    REFERENCES PUNTO_VACUNACION(ID)
ENABLE;

ALTER TABLE OPERADOR_PUNTO_VACUNACION
    ADD CONSTRAINT FK_OPV_FUNCIONARIO
    FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIOS(ID)
ENABLE;



-- Creaación de la tabla CIUDADANOS y especificación de sus restricciones
CREATE TABLE CIUDADANOS
    (ID NUMBER,
    NOMBRE VARCHAR2(50 BYTE) NOT NULL,
    DOCUMENTO VARCHAR2(20 BYTE) NOT NULL,
    ESTADOACTUAL NUMBER NOT NULL,
    FECHANACIMIENTO DATE NOT NULL,
    DIRECCION VARCHAR2(50 BYTE) NOT NULL,
    CIUDAD VARCHAR2(25 BYTE),
    NUMEROCONTACTO VARCHAR2(20 BYTE),
    IDVACUNACION NUMBER NOT NULL,
    IDOFICINAEPS NUMBER NOT NULL,
    IDPUNTOVACUNACION NUMBER,
    IDPROFESION NUMBER NOT NULL,
    IDESTADOSALUD NUMBER NOT NULL,
    IDETAPA NUMBER NOT NULL,
    CONSTRAINT PK_CIUDADANOS PRIMARY KEY(ID));
    
ALTER TABLE CIUDADANOS
    ADD CONSTRAINT UN_DOCUMENTO
    UNIQUE (DOCUMENTO)
ENABLE;

ALTER TABLE CIUDADANOS
    ADD CONSTRAINT FK_C_ESTADO_ACTUAL
    FOREIGN KEY (ESTADOACTUAL)
    REFERENCES ESTADOS_POSIBLES(ID)
ENABLE;

ALTER TABLE CIUDADANOS
    ADD CONSTRAINT FK_C_ETAPA
    FOREIGN KEY (IDETAPA)
    REFERENCES ETAPA(ID)
ENABLE;

ALTER TABLE CIUDADANOS
    ADD CONSTRAINT FK_C_VACUNACION
    FOREIGN KEY (IDVACUNACION)
    REFERENCES VACUNACION(ID)
ENABLE;

ALTER TABLE CIUDADANOS
    ADD CONSTRAINT FK_PROFESION
    FOREIGN KEY (IDPROFESION)
    REFERENCES PROFESION(ID)
ENABLE;
    
ALTER TABLE CIUDADANOS
    ADD CONSTRAINT FK_ESTADO_SALUD
    FOREIGN KEY (IDESTADOSALUD)
    REFERENCES ESTADO_DE_SALUD(ID)
ENABLE;

ALTER TABLE CIUDADANOS
    ADD CONSTRAINT FK_C_OFICINA_EPS
    FOREIGN KEY (IDOFICINAEPS)
    REFERENCES OFICINA_EPS_REGIONAL(ID)
ENABLE;

ALTER TABLE CIUDADANOS
    ADD CONSTRAINT FK_C_PUNTO_VACUNACION
    FOREIGN KEY (IDPUNTOVACUNACION)
    REFERENCES PUNTO_VACUNACION(ID)
ENABLE;

-- Creaación de la tabla DOSIS y especificación de sus restricciones
CREATE TABLE DOSIS
    (ID NUMBER,
    LOTE VARCHAR2(20 BYTE)NOT NULL,
    IDCIUDADANO NUMBER,
    IDOFICINAEPSREGIONAL NUMBER,
    IDPUNTOVACUNACION NUMBER,
    IDVACUNA NUMBER NOT NULL,
    DISPONIBLE NUMBER NOT NULL,
    FECHA_ASIGNAR_EPS DATE,
    FECHA_APLICACION DATE,
    CONSTRAINT PK_DOSIS PRIMARY KEY(ID));

ALTER TABLE DOSIS
    ADD CONSTRAINT FK_D_LOTE
    FOREIGN KEY (LOTE)
    REFERENCES VENCIMIENTO_DOSIS(LOTE)
ENABLE;

ALTER TABLE DOSIS
    ADD CONSTRAINT FK_D_ID_CIUDADANO
    FOREIGN KEY (IDCIUDADANO)
    REFERENCES CIUDADANOS(ID)
ENABLE;

ALTER TABLE DOSIS
    ADD CONSTRAINT FK_D_OFICINA_EPS
    FOREIGN KEY (IDOFICINAEPSREGIONAL)
    REFERENCES OFICINA_EPS_REGIONAL(ID)
ENABLE;

ALTER TABLE DOSIS
    ADD CONSTRAINT FK_D_PUTNO_VACUNACION
    FOREIGN KEY(IDPUNTOVACUNACION)
    REFERENCES PUNTO_VACUNACION(ID)
ENABLE;

ALTER TABLE DOSIS
    ADD CONSTRAINT CK_DISPONIBLE
    CHECK (DISPONIBLE IN (0,1))
ENABLE;

ALTER TABLE DOSIS
    ADD CONSTRAINT FK_D_VACUNA
    FOREIGN KEY (IDVACUNA)
    REFERENCES VACUNA(ID)
ENABLE;

ALTER TABLE DOSIS
    ADD CONSTRAINT CK_FECHA_APLI
    CHECK (FECHA_APLICACION>FECHA_ASIGNAR_EPS)
ENABLE;

-- Creaación de la tabla CITAS y especificación de sus restricciones
CREATE TABLE CITAS
    (ID NUMBER,
    FECHAYHORA TIMESTAMP NOT NULL,
    DURACIONCITA NUMBER NOT NULL,
    ESTADOCITA VARCHAR2 (25 BYTE) NOT NULL,
    IDCIUDADANO NUMBER NOT NULL,
    IDPUNTOVACUNACION NUMBER NOT NULL,
    CONSTRAINT PK_CITAS PRIMARY KEY(ID));
    
ALTER TABLE CITAS
    ADD CONSTRAINT CK_DURACION_CITA
    CHECK (DURACIONCITA>0)
ENABLE;

ALTER TABLE CITAS
    ADD CONSTRAINT CK_ESTADO_CITA
    CHECK (ESTADOCITA IN ('AGENDADA', 'ASISTIDA', 'CANCELADA'))
ENABLE;

ALTER TABLE CITAS
    ADD CONSTRAINT FK_CI_CIUDADANO
    FOREIGN KEY (IDCIUDADANO)
    REFERENCES CIUDADANOS(ID)
ENABLE;

ALTER TABLE CITAS
    ADD CONSTRAINT FK_CI_PUNTO_VACUNACION
    FOREIGN KEY (IDPUNTOVACUNACION)
    REFERENCES PUNTO_VACUNACION(ID)
ENABLE;

-- Creaación de la tabla ESTADO_PROCESO y especificación de sus restricciones
CREATE TABLE ESTADO_PROCESO
    (ID NUMBER,
    ESTADO NUMBER NOT NULL,
    FECHA_CAMBIO DATE NOT NULL,
    COMENTARIO_DESCRIPCION VARCHAR2(250 BYTE),
    ID_CIUDADANO NUMBER NOT NULL,
    CONSTRAINT PK_ESTADO_PROCESO PRIMARY KEY(ID));
    
ALTER TABLE ESTADO_PROCESO
    ADD CONSTRAINT FK_EP_ESTADOS_POSIBLES
    FOREIGN KEY (ESTADO)
    REFERENCES ESTADOS_POSIBLES(ID)
ENABLE;

ALTER TABLE ESTADO_PROCESO
    ADD CONSTRAINT FK_EP_CIUDADANO
    FOREIGN KEY (ID_CIUDADANO)
    REFERENCES CIUDADANOS(ID)
ENABLE;

COMMIT;