--RF12 - REGISTRAR AVANCE EN EL PROCESO DE VACUNACIÓN DE UNA PERSONA

INSERT INTO ESTADO_PROCESO (ID, ESTADO, FECHA_CAMBIO, COMENTARIO_DESCRIPCION, ID_CIUDADANO)
VALUES (31, 6, DATE '2021-05-07', 'Cita asignada a Amanda Ortega', 1);

COMMIT;