--RF14 - DESHABILITAR UN PUNTO DE VACUNACIÓN
UPDATE PUNTO_VACUNACION
SET ESTAHABILITADO=0
WHERE ID=1;

--Esta sentencia hae parte del RF13 también
INSERT INTO CAMBIOS_PUNTO_VACUNACION (ID, DISPONIBLE,FECHACAMBIO,COMENTARIOS,ID_PUNTO_VACUNACION)
values (3, 0,'15/01/2021','Por sospecha de contagio de uno de los miembros del personal se cierra el punto por una semana. Si tenía una cita agendada, esta será reprogramada', 1);

UPDATE CIUDADANOS
SET ESTADOACTUAL=4
WHERE ID IN
    (SELECT IDCIUDADANO
    FROM CITAS
    WHERE IDPUNTODEVACUNACION=1
    AND (FECHAYHORA BETWEEN TO_TIMESTAMP('2021-01-15 00:00:00.0', 'YYYY-MM-DD HH24:MI:SS.FF')
        AND TO_TIMESTAMP('2021-01-22 23:59:00.0', 'YYYY-MM-DD HH24:MI:SS.FF'))
    AND ESTADOCITA='AGENDADA');
    
INSERT INTO ESTADO_PROCESO (ID, ESTADO, FECHA_CAMBIO, COMENTARIO_DESCRIPCION, ID_CIUDADANO)
VALUES (32, 4, DATE '2021-01-15', 'Cita cancelada. Se reasignará una cita lo antes posible en el mismo u otro punto de vacunación', 1);

UPDATE CITAS
SET ESTADOCITA='CANCELADA'
WHERE IDPUNTODEVACUNACION=1
    AND (FECHAYHORA BETWEEN TO_TIMESTAMP('2021-01-15 00:00:00.0', 'YYYY-MM-DD HH24:MI:SS.FF')
        AND TO_TIMESTAMP('2021-01-22 23:59:00.0', 'YYYY-MM-DD HH24:MI:SS.FF'))
    AND ESTADOCITA='AGENDADA';

COMMIT;