--RF2 REGISTRAR LA SECUENCIA DE ESTADOS VÁLIDOS PARA EL PROCESO DE VACUNACIÓN DE UNA PERSONA

INSERT INTO ESTADOS_POSIBLES (ID, DESCRIPCION)
VALUES (1, 'EN_ESPERA');
INSERT INTO ESTADOS_POSIBLES (ID, DESCRIPCION)
VALUES (2,  'PENDIENTE_DE_CONTACTAR');
INSERT INTO ESTADOS_POSIBLES (ID, DESCRIPCION)
VALUES (3,  'NO_QUIERE_VACUNARSE');
INSERT INTO ESTADOS_POSIBLES (ID, DESCRIPCION)
VALUES (4,  'FIRMA_CONSENTIMIENTO_INFORMADO');
INSERT INTO ESTADOS_POSIBLES (ID, DESCRIPCION)
VALUES (5,  'PUNTO_DE_VACUNACION_ASIGNADO');
INSERT INTO ESTADOS_POSIBLES (ID, DESCRIPCION)
VALUES (6,  'CITA_AGENDADA');
INSERT INTO ESTADOS_POSIBLES (ID, DESCRIPCION)
VALUES (7,  'DOSIS_PENDIENTE');
INSERT INTO ESTADOS_POSIBLES (ID, DESCRIPCION)
VALUES (8,  'VACUNADO');
INSERT INTO ESTADOS_POSIBLES (ID, DESCRIPCION)
VALUES (9,  'NO_VACUNABLE');

COMMIT;