-- RF3 - REGISTRAR UNA OFICINA DE EPS REGIONAL
--@Oficina EPS Regional
INSERT INTO OFICINA_EPS_REGIONAL (ID,NOMBRE,NIT,REGION,DIRECCION,NUMERO_CONTACTO,CIUDAD,IDVACUNACION)
VALUES (1,'Compensar Sede Bogotá','ABC123','Bogotá D.C.','Calle 1 #1-1', '300111111', 'Bogotá',1);

COMMIT;