--RF6 REGISTRAR PUNTO DE VACUNACIÓN
--@Punto Vacunación
INSERT INTO PUNTO_VACUNACION (ID, LOCALIZACION, CUPOMAXIMO, MAXCIUDADANOSPORDIA, TOTALVACUNADOS, INFRAESTRUCTURAALMACENAMIENTO, 
                                CAPACIDADALMACENAMIENTODOSIS, IDEPSREGIONAL)
VALUES (1,'Bogotá', 1000, 500, 150, 1, 2000, 1);

INSERT INTO PUNTO_VACUNACION
VALUES (2,'Bogotá', 300, 200, 130, 1, 2000, 1);

COMMIT;