--RF7 - ASIGNAR TALENTO HUMANO A UN PUNTO DE VACUNACIÓN
--@Admin Punto Vacunacion
INSERT INTO ADMIN_PUNTO_VACUNACION (ID_FUNCIONARIO, ID_PUNTO_VACUNACION)
VALUES (3, 1);

INSERT INTO ADMIN_PUNTO_VACUNACION (ID_FUNCIONARIO, ID_PUNTO_VACUNACION)
VALUES (4, 2);

--@Operador Punto Vacunación
INSERT INTO OPERADOR_PUNTO_VACUNACION (ID_FUNCIONARIO, ID_PUNTO_VACUNACION)
VALUES (5, 1);

INSERT INTO OPERADOR_PUNTO_VACUNACION (ID_FUNCIONARIO, ID_PUNTO_VACUNACION)
VALUES (6, 2);

COMMIT;