--RFC1 MOSTRAR TODOS LOS CIUDADANOS ATENDIDOS POR UN PUNTO DE VACUNACIÓN

--Versión administrador plan de vacunación
SELECT *
FROM CIUDADANOS
WHERE ID IN(
    SELECT IDCIUDADANO
    FROM CITAS
    WHERE CITAS.IDPUNTOVACUNACION IN(
        SELECT ID
        FROM PUNTO_VACUNACION
        WHERE IDEPSREGIONAL =
            (SELECT ID
            FROM OFICINA_EPS_REGIONAL
            WHERE REGION='Bogotá D.C.')
        AND FECHAYHORA
            BETWEEN TO_TIMESTAMP('2021-04-11 06:14:00.0', 'YYYY-MM-DD HH24:MI:SS.FF')
            AND TO_TIMESTAMP('2021-08-11 23:59:00.0', 'YYYY-MM-DD HH24:MI:SS.FF')));

--Versión administrador de EPS regional
SELECT *
FROM CIUDADANOS
WHERE ID IN(
    SELECT IDCIUDADANO
    FROM CITAS
    WHERE CITAS.IDPUNTOVACUNACION IN(
        SELECT ID
        FROM PUNTO_VACUNACION
        WHERE IDEPSREGIONAL =
            (SELECT ID_OFICINA_EPS 
            FROM ADMIN_EPS
            WHERE ID_FUNCIONARIO=
                (SELECT ID
                FROM FUNCIONARIOS
                WHERE CORREO='bilbo@gmail.com'))
        AND FECHAYHORA
            BETWEEN TO_TIMESTAMP('2021-04-11 06:14:00.0', 'YYYY-MM-DD HH24:MI:SS.FF')
            AND TO_TIMESTAMP('2021-08-11 23:59:00.0', 'YYYY-MM-DD HH24:MI:SS.FF')));

--Versión administrador punto de vacunación

SELECT *
FROM CIUDADANOS
WHERE ID IN(
    SELECT IDCIUDADANO
    FROM CITAS
    WHERE CITAS.idpuntovacunacion=(
        SELECT ID_PUNTO_VACUNACION
        FROM ADMIN_PUNTO_VACUNACION
        WHERE ID_FUNCIONARIO =
            (SELECT ID 
            FROM FUNCIONARIOS
            WHERE CORREO='carlos@gmail.com'))
        AND FECHAYHORA
            BETWEEN TO_TIMESTAMP('2021-04-11 06:14:00.0', 'YYYY-MM-DD HH24:MI:SS.FF')
            AND TO_TIMESTAMP('2021-08-11 23:59:00.0', 'YYYY-MM-DD HH24:MI:SS.FF'));
    