--RFC13 Consultar a los líderes en gestión del proceso de vacunación
--I EPS que aplican dosis recibidas en menos de X dias
SELECT idoficinaepsregional, COUNT(*)
FROM DOSIS
GROUP BY idoficinaepsregional
ORDER BY idoficinaepsregional;

SELECT idoficinaepsregional, COUNT(*)
FROM DOSIS
WHERE IDCIUDADANO IS NOT NULL
GROUP BY idoficinaepsregional
ORDER BY idoficinaepsregional;

SELECT IDOFICINAEPSREGIONAL,COUNT(*)
FROM DOSIS
WHERE IDCIUDADANO IS NOT NULL
    AND (FECHA_APLICACION-FECHA_ASIGNAR_EPS)<3
GROUP BY IDOFICINAEPSREGIONAL;

SELECT IDOFICINAEPSREGIONAL,COUNT(*)
FROM DOSIS
WHERE IDCIUDADANO IS NOT NULL
    AND (FECHA_APLICACION-FECHA_ASIGNAR_EPS)<5
GROUP BY IDOFICINAEPSREGIONAL;

SELECT IDOFICINAEPSREGIONAL,COUNT(*)
FROM DOSIS
WHERE IDCIUDADANO IS NOT NULL
    AND (FECHA_APLICACION-FECHA_ASIGNAR_EPS)<10
GROUP BY IDOFICINAEPSREGIONAL;