--RFC13 Consultar a los líderes en gestión del proceso de vacunación
--II Puestos de vacunación con mayor proporcion de personas vacunadas para la capacidad de vacunacion por días
    
SELECT CITAS.IDPUNTOVACUNACION, COUNT(*),PUNTO_VACUNACION.MAXCIUDADANOSPORDIA
FROM CITAS
INNER JOIN PUNTO_VACUNACION ON punto_vacunacion.ID=CITAS.IDPUNTOVACUNACION
WHERE fechayhora BETWEEN TO_TIMESTAMP('2021-05-20 00:00:00.0', 'YYYY-MM-DD HH24:MI:SS.FF') AND TO_TIMESTAMP('2021-05-20 23:59:00.0', 'YYYY-MM-DD HH24:MI:SS.FF')
    AND ESTADOCITA='ASISTIDA'
GROUP BY IDPUNTOVACUNACION,MAXCIUDADANOSPORDIA;

SELECT CITAS.IDPUNTOVACUNACION, COUNT(*),PUNTO_VACUNACION.MAXCIUDADANOSPORDIA*3
FROM CITAS
INNER JOIN PUNTO_VACUNACION ON punto_vacunacion.ID=CITAS.IDPUNTOVACUNACION
WHERE fechayhora BETWEEN TO_TIMESTAMP('2021-05-20 00:00:00.0', 'YYYY-MM-DD HH24:MI:SS.FF') AND TO_TIMESTAMP('2021-05-23 23:59:00.0', 'YYYY-MM-DD HH24:MI:SS.FF')
    AND ESTADOCITA='ASISTIDA'
GROUP BY IDPUNTOVACUNACION,MAXCIUDADANOSPORDIA;

SELECT CITAS.IDPUNTOVACUNACION, COUNT(*),PUNTO_VACUNACION.MAXCIUDADANOSPORDIA*5
FROM CITAS
INNER JOIN PUNTO_VACUNACION ON punto_vacunacion.ID=CITAS.IDPUNTOVACUNACION
WHERE fechayhora BETWEEN TO_TIMESTAMP('2021-05-20 00:00:00.0', 'YYYY-MM-DD HH24:MI:SS.FF') AND TO_TIMESTAMP('2021-05-25 23:59:00.0', 'YYYY-MM-DD HH24:MI:SS.FF')
    AND ESTADOCITA='ASISTIDA'
GROUP BY IDPUNTOVACUNACION,MAXCIUDADANOSPORDIA;