--RFC3 MOSTRAR EL ÍNDICE DE VACUNACIÓN PARA UN GRUPO POBLACIONAL

--Para una región
SELECT COUNT(*)
FROM CIUDADANOS
WHERE IDOFICINAEPS=1
    AND ESTADOACTUAL BETWEEN 2 AND 7;

SELECT COUNT(*)
FROM CIUDADANOS
WHERE IDOFICINAEPS=1
    AND ESTADOACTUAL =8;
    
--Para una etapa del proces
SELECT COUNT(*)
FROM CIUDADANOS
WHERE IDETAPA=1
    AND ESTADOACTUAL BETWEEN 2 AND 7;

SELECT COUNT(*)
FROM CIUDADANOS
WHERE IDETAPA=1
    AND ESTADOACTUAL =8;