SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='PRESUPUESTO' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='CANT_SEDES' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='GRADO_ALCOHOL' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='HORARIO' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='PRESUPUESTO' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='HORARIO' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='ID_BEBEDOR' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='ID_BEBEDOR' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='ID_BEBIDA' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='ID_BEBIDA' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='ID_BEBEDOR' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='HORARIO' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='ID_BEBIDA' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='ID_BEBEDOR' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='ID_BEBIDA' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;

SELECT COLUMN_NAME, TABLE_NAME, COUNT(CONSTRAINT_NAME)
    FROM all_cons_columns
    WHERE COLUMN_NAME='HORARIO' AND owner = 'PARRANDEROS' 
GROUP BY COLUMN_NAME, TABLE_NAME;